application: 
  port: 8000 
database:
  host: "localhost"
  port: 5432
  username: "postgres" 
  password: "password" 
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "justin@lgi.ai"
  authorization_token: "57030955-eb9c-4730-96a6-8b7e6dbc2863"
  timeout_milliseconds: 10000